# fly.toml app configuration file generated for botagendamentos on 2025-02-14T19:03:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml app configuration file for botagendamentos

app = "botagendamentos"
primary_region = "gig"

[build]

# Define que o processo principal do bot será mantido rodando continuamente
[processes]
  app = "python main.py"

# Garante que a máquina não seja parada automaticamente
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
